/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_auroraagent_free: (a: number, b: number) => void;
export const auroraagent_new: (a: number, b: number) => any;
export const auroraagent_start: (a: number) => any;
export const auroraagent_process_prompt: (a: number, b: number, c: number) => any;
export const auroraagent_get_state: (a: number) => any;
export const auroraagent_get_did: (a: number) => [number, number];
export const auroraagent_get_peer_count: (a: number) => number;
export const auroraagent_get_public_key: (a: number) => [number, number];
export const auroraagent_sign_message: (a: number, b: number, c: number) => any;
export const auroraagent_verify_signature: (a: number, b: number, c: number, d: number, e: number, f: number) => any;
export const auroraagent_shutdown: (a: number) => any;
export const main: () => void;
export const create_agent: (a: any) => any;
export const get_version: () => [number, number];
export const health_check: () => number;
export const sign_message: (a: number, b: number, c: number) => any;
export const verify_signature: (a: number, b: number, c: number, d: number, e: number, f: number) => any;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export_5: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const closure80_externref_shim: (a: number, b: number, c: any) => void;
export const closure105_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_start: () => void;
