name: CopyToS3
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id:  ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY_SECRET }}
          aws-region:  ${{ vars.REGION}}
      - name: Copy Templates
        run: aws s3 sync ./ s3://${{vars.CODE_BUCKET}}